import { registerNode } from "@/engine/registry";
import { imageSourceNode } from "./source/image-source";
import { paintNode } from "./source/paint";
import { solidColorNode } from "./source/solid-color";
import { gradientNode } from "./source/gradient";
import { perlinNoiseNode } from "./source/perlin-noise";
import { voronoiNode } from "./source/voronoi";
import { fractureNode } from "./source/fracture";
import { sceneTimeNode } from "./source/scene-time";
import { uvCoordsNode } from "./source/uv-coords";
import { textNode } from "./source/text";
import { cursorNode } from "./source/cursor";
import { videoNode } from "./source/video";
import { audioSourceNode } from "./source/audio";
import { webcamSourceNode } from "./source/webcam";
import { splineDrawNode } from "./source/spline-draw";
import { svgSourceNode } from "./source/svg-source";
import { circleNode } from "./source/circle";
import { rectangleNode } from "./source/rectangle";
import { imageGenerateNode } from "./source/image-generate";
import { shapeCellsNode } from "./source/shape-cells";
import { sampleAlongPathNode } from "./effect/sample-along-path";
import { resampleNode } from "./effect/resample";
import { pointsOnPathNode } from "./effect/points-on-path";
import { offsetPathNode } from "./effect/offset-path";
import { strokeNode } from "./effect/stroke";
import { fillNode } from "./effect/fill";
import { rasterizeSplineNode } from "./effect/rasterize-spline";
import { pointNode } from "./source/point";
import { scatterPointsNode } from "./effect/scatter-points";
import { copyToPointsNode } from "./effect/copy-to-points";
import { remapNode } from "./effect/remap";
import { modulatePointsNode } from "./effect/modulate-points";
import { modulateSplinesNode } from "./effect/modulate-splines";
import { simulationStartNode } from "./effect/simulation-start";
import { simulationEndNode } from "./effect/simulation-end";
import { pointEmitterNode } from "./effect/emitter-point";
import { imageMaskEmitterNode } from "./effect/emitter-image-mask";
import { gravityForceNode } from "./effect/force-gravity";
import { dragForceNode } from "./effect/force-drag";
import { pointForceNode } from "./effect/force-point";
import { vortexForceNode } from "./effect/force-vortex";
import { windForceNode } from "./effect/force-wind";
import { turbulenceForceNode } from "./effect/force-turbulence";
import { particleSimulatorNode } from "./effect/particle-simulator";
import { particlesToImageNode } from "./effect/particles-to-image";
import { webgpuParticleTestNode } from "./effect/webgpu-particle-test";
import { circleColliderNode } from "./effect/collider-circle";
import { lineColliderNode } from "./effect/collider-line";
import { imageMaskColliderNode } from "./effect/collider-image-mask";
import { reactionDiffusionNode } from "./effect/reaction-diffusion";
import { accumulatorNode } from "./effect/accumulator";
import { sharpenNode } from "./effect/sharpen";
import { grainNode } from "./effect/grain";
import { bgRemoveNode } from "./effect/bg-remove";
import { edgeDetectNode } from "./effect/edge-detect";
import { objectTrackerNode } from "./effect/object-tracker";
import { handTrackerNode } from "./effect/hand-tracker";
import { groupNode } from "./effect/group";
import { groupPickNode } from "./effect/group-pick";
import { groupLengthNode } from "./effect/group-length";
import { asciiNode } from "./effect/ascii";
import { splitVec2Node } from "./effect/split-vec2";
import { combineVec2Node } from "./effect/combine-vec2";
import { setPositionNode } from "./effect/set-position";
import { bloomNode } from "./effect/bloom";
import { lensFlareNode } from "./effect/lens-flare";
import { mergeNode } from "./effect/merge";
import { gaussianBlurNode } from "./effect/gaussian-blur";
import { ditherNode } from "./effect/dither";
import { colorRampNode } from "./effect/color-ramp";
import { colorCorrectionNode } from "./effect/color-correction";
import { transformNode } from "./effect/transform";
import { mathNode } from "./effect/math";
import { trailsNode } from "./effect/trails";
import { stippleNode } from "./effect/stipple";
import { displaceNode } from "./effect/displace";
import { arrayNode } from "./effect/array";
import { proximityMergeNode } from "./effect/proximity-merge";
import { connectPointsNode } from "./effect/connect-points";
import { lissajous2DNode, lissajous3DNode } from "./effect/lissajous";
import { jitterNode } from "./effect/jitter";
import { thresholdNode } from "./effect/threshold";
import { constantNode } from "./source/constant";
import { lfoNode } from "./source/lfo";
import { smoothNode } from "./effect/smooth";
import { switchNode } from "./effect/switch";
import { sampleTextureAtPointsNode } from "./effect/sample-texture-at-points";
import { filterPointsNode } from "./effect/filter-points";
import { lerpNode } from "./effect/lerp";
import { polarCoordsNode } from "./effect/polar-coords";
import { vec2LiteralNode } from "./source/vec2-literal";
import { vec3LiteralNode } from "./source/vec3-literal";
import { colorLiteralNode } from "./source/color-literal";
import { randomNode } from "./source/random";
import { compareNode } from "./effect/compare";
import { logicNode } from "./effect/logic";
import { clampNode } from "./effect/clamp";
import { sdfCircleNode } from "./sdf/circle";
import { sdfRectangleNode } from "./sdf/rectangle";
import { sdfUnionNode } from "./sdf/union";
import { sdfIntersectionNode } from "./sdf/intersection";
import { sdfSubtractionNode } from "./sdf/subtraction";
import { sdfSmoothUnionNode } from "./sdf/smooth-union";
import { sdfRoundNode } from "./sdf/round";
import { sdfRasterizeNode } from "./sdf/rasterize";
import { sdfLineSegmentNode } from "./sdf/line-segment";
import { sdfPolygonNode } from "./sdf/polygon";
import { sdfTriangleNode } from "./sdf/triangle";
import { sdfStarNode } from "./sdf/star";
import { sdfSplineNode } from "./sdf/spline";
import { sdfBevelNode } from "./sdf/sdf-bevel";
import { bevelEmbossNode } from "./effect/bevel-emboss";
import { sdfSmoothIntersectionNode } from "./sdf/smooth-intersection";
import { sdfSmoothSubtractionNode } from "./sdf/smooth-subtraction";
import { sdfTranslateNode } from "./sdf/sdf-translate";
import { sdfScaleNode } from "./sdf/sdf-scale";
import { sdfRotateNode } from "./sdf/sdf-rotate";
import { sdfRepeatNode } from "./sdf/sdf-repeat";
import { sdfMirrorNode } from "./sdf/sdf-mirror";
import { sdfPolarNode } from "./sdf/sdf-polar";
import { sdfTwistNode } from "./sdf/sdf-twist";
import { sdfOnionNode } from "./sdf/onion";
import { sdfDisplaceNode } from "./sdf/displace";
import { sdfToDistanceImageNode } from "./sdf/to-distance-image";
import { sdfToMaskNode } from "./sdf/to-mask";
import { sdfToSplineNode } from "./sdf/to-spline";
import { outputNode } from "./output/output";

let registered = false;

export function registerAllNodes() {
  if (registered) return;
  registerNode(imageSourceNode);
  registerNode(paintNode);
  registerNode(solidColorNode);
  registerNode(gradientNode);
  registerNode(perlinNoiseNode);
  // Back-compat: projects saved before the rename from "perlin-noise" to
  // "noise" keep loading via the old type string.
  registerNode({ ...perlinNoiseNode, type: "perlin-noise" });
  registerNode(voronoiNode);
  registerNode(fractureNode);
  registerNode(sceneTimeNode);
  registerNode(uvCoordsNode);
  // Back-compat alias — projects saved before the rename reference the
  // old type string; serving the same def under both keeps them loading.
  registerNode({ ...uvCoordsNode, type: "uv-coords" });
  registerNode(textNode);
  registerNode(cursorNode);
  registerNode(videoNode);
  registerNode(audioSourceNode);
  registerNode(webcamSourceNode);
  registerNode(splineDrawNode);
  registerNode(svgSourceNode);
  registerNode(circleNode);
  registerNode(rectangleNode);
  registerNode(imageGenerateNode);
  registerNode(shapeCellsNode);
  registerNode(sampleAlongPathNode);
  registerNode(resampleNode);
  registerNode(pointsOnPathNode);
  registerNode(offsetPathNode);
  registerNode(strokeNode);
  registerNode(fillNode);
  registerNode(rasterizeSplineNode);
  registerNode(pointNode);
  registerNode(scatterPointsNode);
  registerNode(copyToPointsNode);
  registerNode(remapNode);
  registerNode(modulatePointsNode);
  registerNode(modulateSplinesNode);
  registerNode(simulationStartNode);
  registerNode(simulationEndNode);
  registerNode(pointEmitterNode);
  registerNode(imageMaskEmitterNode);
  registerNode(gravityForceNode);
  registerNode(dragForceNode);
  registerNode(pointForceNode);
  registerNode(vortexForceNode);
  registerNode(windForceNode);
  registerNode(turbulenceForceNode);
  registerNode(circleColliderNode);
  registerNode(lineColliderNode);
  registerNode(imageMaskColliderNode);
  registerNode(particleSimulatorNode);
  registerNode(particlesToImageNode);
  registerNode(webgpuParticleTestNode);
  registerNode(reactionDiffusionNode);
  registerNode(accumulatorNode);
  registerNode(sharpenNode);
  registerNode(grainNode);
  registerNode(bgRemoveNode);
  registerNode(edgeDetectNode);
  registerNode(objectTrackerNode);
  registerNode(handTrackerNode);
  registerNode(groupNode);
  registerNode(groupPickNode);
  registerNode(groupLengthNode);
  registerNode(asciiNode);
  registerNode(splitVec2Node);
  registerNode(combineVec2Node);
  registerNode(setPositionNode);
  registerNode(bloomNode);
  registerNode(lensFlareNode);
  registerNode(mergeNode);
  registerNode(gaussianBlurNode);
  registerNode(ditherNode);
  registerNode(colorRampNode);
  registerNode(colorCorrectionNode);
  registerNode(transformNode);
  registerNode(mathNode);
  registerNode(trailsNode);
  registerNode(stippleNode);
  registerNode(displaceNode);
  registerNode(arrayNode);
  registerNode(proximityMergeNode);
  registerNode(connectPointsNode);
  registerNode(lissajous2DNode);
  registerNode(lissajous3DNode);
  registerNode(jitterNode);
  registerNode(thresholdNode);
  registerNode(constantNode);
  registerNode(lfoNode);
  registerNode(smoothNode);
  registerNode(switchNode);
  registerNode(sampleTextureAtPointsNode);
  registerNode(filterPointsNode);
  registerNode(lerpNode);
  registerNode(polarCoordsNode);
  registerNode(vec2LiteralNode);
  registerNode(vec3LiteralNode);
  registerNode(colorLiteralNode);
  registerNode(randomNode);
  registerNode(compareNode);
  registerNode(logicNode);
  registerNode(clampNode);
  registerNode(sdfCircleNode);
  registerNode(sdfRectangleNode);
  registerNode(sdfUnionNode);
  registerNode(sdfIntersectionNode);
  registerNode(sdfSubtractionNode);
  registerNode(sdfSmoothUnionNode);
  registerNode(sdfRoundNode);
  registerNode(sdfRasterizeNode);
  registerNode(sdfLineSegmentNode);
  registerNode(sdfPolygonNode);
  registerNode(sdfTriangleNode);
  registerNode(sdfStarNode);
  registerNode(sdfSplineNode);
  registerNode(sdfBevelNode);
  registerNode(bevelEmbossNode);
  registerNode(sdfSmoothIntersectionNode);
  registerNode(sdfSmoothSubtractionNode);
  registerNode(sdfTranslateNode);
  registerNode(sdfScaleNode);
  registerNode(sdfRotateNode);
  registerNode(sdfRepeatNode);
  registerNode(sdfMirrorNode);
  registerNode(sdfPolarNode);
  registerNode(sdfTwistNode);
  registerNode(sdfOnionNode);
  registerNode(sdfDisplaceNode);
  registerNode(sdfToDistanceImageNode);
  registerNode(sdfToMaskNode);
  registerNode(sdfToSplineNode);
  registerNode(outputNode);
  registered = true;
}
