import { registerNode } from "@/engine/registry";
import { imageSourceNode } from "./source/image-source";
import { paintNode } from "./source/paint";
import { solidColorNode } from "./source/solid-color";
import { gradientNode } from "./source/gradient";
import { perlinNoiseNode } from "./source/perlin-noise";
import { voronoiNode, fractureLegacyNode } from "./source/voronoi";
import { sceneTimeNode } from "./source/scene-time";
import { uvCoordsNode } from "./source/uv-coords";
import { textNode } from "./source/text";
import { cursorNode } from "./source/cursor";
import { cursorTrailPointsNode } from "./source/cursor-trail-points";
import { pointerNode } from "./source/pointer";
import { videoNode } from "./source/video";
import { audioSourceNode } from "./source/audio";
import { audioBandsNode } from "./audio/bands";
import { audioPitchNode } from "./audio/pitch";
import { audioSpectralNode } from "./audio/spectral";
import { audioOscillatorNode } from "./audio/oscillator";
import { audioFilterNode } from "./audio/filter";
import { audioNoiseNode } from "./audio/noise";
import { audioPlayerNode } from "./audio/player";
import { audioSynthNode } from "./audio/synth";
import { audioFmSynthNode } from "./audio/fm-synth";
import { audioSamplerNode } from "./audio/sampler";
import { audioEq3Node } from "./audio/eq3";
import { audioDistortionNode } from "./audio/distortion";
import { audioBitcrusherNode } from "./audio/bitcrusher";
import { audioCompressorNode } from "./audio/compressor";
import { audioLimiterNode } from "./audio/limiter";
import { audioChannelNode } from "./audio/channel";
import { audioDelayNode } from "./audio/delay";
import { audioReverbNode } from "./audio/reverb";
import { audioChorusNode } from "./audio/chorus";
import { audioPhaserNode } from "./audio/phaser";
import { audioMergeNode } from "./audio/audio-merge";
import { audioCrossfadeNode } from "./audio/crossfade";
import { audioStepPatternNode } from "./audio/step-pattern";
import { audioTransposeNode } from "./audio/transpose";
import { audioLfoNode } from "./audio/audio-lfo";
import { midiEditorNode } from "./audio/midi-editor";
import { webcamSourceNode } from "./source/webcam";
import { splineDrawNode } from "./source/spline-draw";
import { svgSourceNode } from "./source/svg-source";
import { circleNode } from "./source/circle";
import { rectangleNode } from "./source/rectangle";
import { spiralNode } from "./source/spiral";
import { crossNode } from "./source/cross";
import { polygonNode } from "./source/polygon";
import { starNode } from "./source/star";
import { arcNode } from "./source/arc";
import { waveNode } from "./source/wave";
import { arrowNode } from "./source/arrow";
import { imageGenerateNode } from "./source/image-generate";
import { shapeCellsNode } from "./source/shape-cells";
import { frameNode } from "./source/frame";
import { cube3DTestNode } from "./source/cube-3d-test";
import {
  cube3DNode,
  sphere3DNode,
  plane3DNode,
  cylinder3DNode,
  cone3DNode,
  torus3DNode,
} from "./three/primitives";
import { light3DNode } from "./three/light";
import { camera3DNode } from "./three/camera";
import { import3DNode } from "./three/import-3d";
import { sceneMergeNode } from "./three/scene-merge";
import { sceneRenderNode } from "./three/scene-render";
import { scatterPoints3DNode } from "./three/scatter-points-3d";
import { copyToPoints3DNode } from "./three/copy-to-points-3d";
import { extrudeFaces3DNode } from "./three/extrude-faces";
import { material3DNode } from "./three/material";
import { bump3DNode } from "./three/bump";
import { textureProjection3DNode } from "./three/texture-projection";
import { realizeInstances3DNode } from "./three/realize-instances";
import { instanceColor3DNode } from "./three/instance-color";
import { extrudeSpline3DNode } from "./three/extrude-spline";
import { lathe3DNode } from "./three/lathe";
import { transform3DNode } from "./three/transform-3d";
import { array3DNode } from "./three/array-3d";
import { instanceTransform3DNode } from "./three/instance-transform";
import { alignToCamera3DNode } from "./three/align-to-camera";
import { projectToScreen3DNode } from "./three/project-to-screen";
import { bevel3DNode } from "./three/bevel";
import { spline3DNode } from "./three/spline-3d";
import { bezierPath3DNode } from "./three/bezier-path-3d";
import {
  rectCurve3DNode,
  circleCurve3DNode,
  polygonCurve3DNode,
} from "./three/curve-primitives";
import { autoLayoutNode } from "./effect/autolayout";
import { sampleAlongPathNode } from "./effect/sample-along-path";
import { resampleNode } from "./effect/resample";
import { optimizePathNode } from "./effect/optimize-path";
import { pointsOnPathNode } from "./effect/points-on-path";
import { offsetPathNode } from "./effect/offset-path";
import { repeatPathNode } from "./effect/repeat-path";
import { trimPathNode } from "./effect/trim-path";
import { roundCornersNode } from "./effect/round-corners";
import { bezierHandlesNode } from "./effect/bezier-handles";
import { strokeNode } from "./effect/stroke";
import { fillNode } from "./effect/fill";
import { rasterizeSplineNode } from "./effect/rasterize-spline";
import { splineBooleanNode } from "./effect/spline-boolean";
import { splineMergeNode } from "./effect/spline-merge";
import { blendIntersectionsNode } from "./effect/blend-intersections";
import { splineMorphNode } from "./effect/spline-morph";
import { splineInterpolateNode } from "./effect/spline-interpolate";
import { pointsToSplineNode } from "./effect/points-to-spline";
import { splineTrailsNode } from "./effect/spline-trails";
import { loopWeaveNode } from "./effect/loop-weave";
import { setSplineTypeNode } from "./effect/set-spline-type";
import { relaxNode } from "./effect/relax";
import { ropeSimulatorNode } from "./effect/rope-simulator";
import { rigidBodySimulatorNode } from "./effect/rigid-body-simulator";
import { shortestPathNode } from "./effect/shortest-path";
import { pointNode } from "./source/point";
import { gridNode } from "./source/grid";
import { scatterPointsNode } from "./effect/scatter-points";
import { copyToPointsNode } from "./effect/copy-to-points";
import { remapNode } from "./effect/remap";
import { modulatePointsNode } from "./effect/modulate-points";
import { advectPointsNode } from "./effect/advect-points";
import { advectImageNode } from "./effect/advect-image";
import { splineFlowFieldNode } from "./effect/spline-flow-field";
import { flowObstacleNode } from "./effect/flow-obstacle";
import { imageFlowFieldNode } from "./effect/image-flow-field";
import { flowBlurNode } from "./effect/flow-blur";
import { kuwaharaNode } from "./effect/kuwahara";
import { flowBilateralNode } from "./effect/flow-bilateral";
import { shockFilterNode } from "./effect/shock-filter";
import { lineArtNode } from "./effect/line-art";
import { modulateSplinesNode } from "./effect/modulate-splines";
import { pointExpressionNode } from "./effect/point-expression";
import { pointsToTextNode } from "./effect/points-to-text";
import { pointLabelsNode } from "./effect/point-labels";
import { simulationStartNode } from "./effect/simulation-start";
import { simulationEndNode } from "./effect/simulation-end";
import { pointEmitterNode } from "./effect/emitter-point";
import { imageMaskEmitterNode } from "./effect/emitter-image-mask";
import { gravityForceNode } from "./effect/force-gravity";
import { dragForceNode } from "./effect/force-drag";
import { pointForceNode } from "./effect/force-point";
import { vortexForceNode } from "./effect/force-vortex";
import { windForceNode } from "./effect/force-wind";
import { turbulenceForceNode } from "./effect/force-turbulence";
import { particleSimulatorNode } from "./effect/particle-simulator";
import { particlesToImageNode } from "./effect/particles-to-image";
import { webgpuParticleTestNode } from "./effect/webgpu-particle-test";
import { circleColliderNode } from "./effect/collider-circle";
import { lineColliderNode } from "./effect/collider-line";
import { imageMaskColliderNode } from "./effect/collider-image-mask";
import { reactionDiffusionNode } from "./effect/reaction-diffusion";
import { watercolorInkNode } from "./effect/watercolor-ink";
import { physarumNode } from "./effect/physarum";
import { fluidSimulatorNode } from "./effect/fluid-simulator";
import { matterSimulatorNode } from "./effect/matter-simulator";
import { pointsToSurfaceNode } from "./effect/points-to-surface";
import { diffusionCurvesNode } from "./effect/diffusion-curves";
import { accumulatorNode } from "./effect/accumulator";
import { triggerEnvelopeNode } from "./effect/trigger-envelope";
import { sampleHoldNode } from "./effect/sample-hold";
import { hitRegionNode } from "./effect/hit-region";
import { dragPointsNode } from "./effect/drag-points";
import { draggableNode } from "./effect/draggable";
import { sharpenNode } from "./effect/sharpen";
import { grainNode } from "./effect/grain";
import { bgRemoveNode } from "./effect/bg-remove";
import { segmentAnythingNode } from "./effect/segment";
import { depthAnythingNode } from "./effect/depth-anything";
import { edgeDetectNode } from "./effect/edge-detect";
import { objectTrackerNode } from "./effect/object-tracker";
import { trackerPointNode } from "./effect/tracker-point";
import { handTrackerNode } from "./effect/hand-tracker";
import { collectNode } from "./effect/collect";
import { nodeGroupNode } from "./group/node-group";
import { groupInputNode } from "./group/group-input";
import { groupOutputNode } from "./group/group-output";
import { layerNode } from "./group/layer";
import { iterateNode } from "./group/iterate";
import { iterateInputNode } from "./group/iterate-input";
import { iterateFeedNode } from "./group/iterate-feed";
import { groupPickNode } from "./effect/group-pick";
import { groupLengthNode } from "./effect/group-length";
import { asciiNode } from "./effect/ascii";
import { splitVec2Node } from "./effect/split-vec2";
import { combineVec2Node } from "./effect/combine-vec2";
import { setPositionNode } from "./effect/set-position";
import { bloomNode } from "./effect/bloom";
import { lensFlareNode } from "./effect/lens-flare";
import { mergeNode } from "./effect/merge";
import { blurNode, gaussianBlurLegacyNode } from "./effect/blur";
import { ditherNode } from "./effect/dither";
import { posterizeNode } from "./effect/posterize";
import { pixelateNode } from "./effect/pixelate";
import { adaptivePixelateNode } from "./effect/adaptive-pixelate";
import { bentoSliceNode } from "./effect/bento-slice";
import { chromaticAberrationNode } from "./effect/chromatic-aberration";
import { liquidGlassNode } from "./effect/liquid-glass";
import { colorRampNode } from "./effect/color-ramp";
import { keyerNode } from "./effect/keyer";
import { colorCorrectionNode } from "./effect/color-correction";
import { rgbCurvesNode } from "./effect/rgb-curves";
import { lutNode } from "./effect/lut";
import { colorSpaceTransformNode } from "./effect/color-space-transform";
import { transformNode } from "./effect/transform";
import { boundingBoxNode } from "./effect/bounding-box";
import { mathNode } from "./effect/math";
import { rerouteNode } from "./effect/reroute";
import { frameZoneNode } from "./effect/frame-zone";
import { expressionNode } from "./effect/expression";
import { trailsNode } from "./effect/trails";
import { datamoshNode } from "./effect/datamosh";
import { stippleNode } from "./effect/stipple";
import { displaceNode } from "./effect/displace";
import { arrayNode } from "./effect/array";
import { mirrorNode } from "./effect/mirror";
import { proximityMergeNode } from "./effect/proximity-merge";
import { connectPointsNode } from "./effect/connect-points";
import { splineIntersectionsNode } from "./effect/spline-intersections";
import { splineToPointsNode } from "./effect/spline-to-points";
import { stringArtNode } from "./effect/string-art";
import { lissajous2DNode, lissajous3DNode } from "./effect/lissajous";
import { spaceFillNode } from "./source/space-fill";
import { accretiveGrowthNode } from "./source/accretive-growth";
import { lSystemNode } from "./source/l-system";
import { differentialGrowthNode } from "./effect/differential-growth";
import { behavioralGrowthNode } from "./effect/behavioral-growth";
import { jitterNode } from "./effect/jitter";
import { thresholdNode } from "./effect/threshold";
import { constantNode } from "./source/constant";
import { animatedValueNode } from "./source/animated-value";
import { timeOffsetNode } from "./effect/time-offset";
import { timeOffsetFeedNode } from "./effect/time-offset-feed";
import { lfoNode } from "./source/lfo";
import { wedgeNode } from "./source/wedge";
import { smoothNode } from "./effect/smooth";
import { switchNode } from "./effect/switch";
import { sampleTextureAtPointsNode } from "./effect/sample-texture-at-points";
import { setNamedAttributeNode } from "./effect/set-named-attribute";
import { attributeMathNode } from "./effect/attribute-math";
import { attributeBlurNode } from "./effect/attribute-blur";
import { attributeTransferNode } from "./effect/attribute-transfer";
import { glslExpressionNode } from "./effect/glsl-expression";
import { mapAttributeNode } from "./effect/map-attribute";
import { filterPointsNode } from "./effect/filter-points";
import { filterSplinesNode } from "./effect/filter-splines";
import { lerpNode } from "./effect/lerp";
import { polarCoordsNode } from "./effect/polar-coords";
import { vec2LiteralNode } from "./source/vec2-literal";
import { vec3LiteralNode } from "./source/vec3-literal";
import { colorLiteralNode } from "./source/color-literal";
import { stringLiteralNode } from "./source/string-literal";
import { csvNode } from "./source/csv";
import { listNode } from "./source/list";
import { numberToStringNode } from "./effect/number-to-string";
import { randomNode } from "./source/random";
import { compareNode } from "./effect/compare";
import { logicNode } from "./effect/logic";
import { clampNode } from "./effect/clamp";
import { floatCurveNode } from "./effect/float-curve";
import { sdfCircleNode } from "./sdf/circle";
import { sdfRectangleNode } from "./sdf/rectangle";
import { sdfUnionNode } from "./sdf/union";
import { sdfIntersectionNode } from "./sdf/intersection";
import { sdfSubtractionNode } from "./sdf/subtraction";
import { sdfSmoothUnionNode } from "./sdf/smooth-union";
import { sdfRoundNode } from "./sdf/round";
import { sdfRasterizeNode } from "./sdf/rasterize";
import { sdfMaterialNode } from "./sdf/material";
import { sdfShadeNode } from "./sdf/shade";
import { sdfLineSegmentNode } from "./sdf/line-segment";
import { sdfPolygonNode } from "./sdf/polygon";
import { sdfTriangleNode } from "./sdf/triangle";
import { sdfStarNode } from "./sdf/star";
import { sdfSplineNode } from "./sdf/spline";
import { sdfBevelNode } from "./sdf/sdf-bevel";
import { bevelEmbossNode } from "./effect/bevel-emboss";
import { sdfSmoothIntersectionNode } from "./sdf/smooth-intersection";
import { sdfSmoothSubtractionNode } from "./sdf/smooth-subtraction";
import { sdfMorphNode } from "./sdf/morph";
import { sdfFromImageNode } from "./sdf/from-image";
import { sdfTranslateNode } from "./sdf/sdf-translate";
import { sdfScaleNode } from "./sdf/sdf-scale";
import { sdfRotateNode } from "./sdf/sdf-rotate";
import { sdfRepeatNode } from "./sdf/sdf-repeat";
import { sdfMirrorNode } from "./sdf/sdf-mirror";
import { sdfPolarNode } from "./sdf/sdf-polar";
import { sdfTwistNode } from "./sdf/sdf-twist";
import { sdfOnionNode } from "./sdf/onion";
import { sdfDisplaceNode } from "./sdf/displace";
import { sdfToDistanceImageNode } from "./sdf/to-distance-image";
import { sdfToMaskNode } from "./sdf/to-mask";
import { sdfToSplineNode } from "./sdf/to-spline";
import { outputNode } from "./output/output";
import { renderQueueNode } from "./output/render-queue";
import { svgExportNode } from "./output/svg-export";

let registered = false;

export function registerAllNodes() {
  if (registered) return;
  registerNode(imageSourceNode);
  registerNode(paintNode);
  registerNode(solidColorNode);
  registerNode(gradientNode);
  registerNode(perlinNoiseNode);
  // Back-compat: projects saved before the rename from "perlin-noise" to
  // "noise" keep loading via the old type string.
  registerNode({ ...perlinNoiseNode, type: "perlin-noise", hidden: true });
  registerNode(voronoiNode);
  // Fracture merged into Voronoi as its "scatter" source (073026) — the
  // legacy type stays registered (hidden) so old saves load unchanged.
  registerNode(fractureLegacyNode);
  registerNode(sceneTimeNode);
  registerNode(uvCoordsNode);
  // Back-compat alias — projects saved before the rename reference the
  // old type string; serving the same def under both keeps them loading.
  registerNode({ ...uvCoordsNode, type: "uv-coords", hidden: true });
  registerNode(textNode);
  registerNode(cursorNode);
  registerNode(cursorTrailPointsNode);
  registerNode(pointerNode);
  registerNode(videoNode);
  registerNode(cube3DTestNode);
  // 3D node family (M1) — convergent dataflow into Scene Render.
  registerNode(cube3DNode);
  registerNode(sphere3DNode);
  registerNode(plane3DNode);
  registerNode(cylinder3DNode);
  registerNode(cone3DNode);
  registerNode(torus3DNode);
  registerNode(light3DNode);
  registerNode(camera3DNode);
  registerNode(import3DNode);
  registerNode(sceneMergeNode);
  registerNode(sceneRenderNode);
  // Wave 2 (081026_3d-geometry-points-materials.md M2–M4): 3D instancing,
  // modeling, materials.
  registerNode(scatterPoints3DNode);
  registerNode(copyToPoints3DNode);
  registerNode(extrudeFaces3DNode);
  registerNode(material3DNode);
  registerNode(bump3DNode);
  registerNode(textureProjection3DNode);
  // M4.5: the instance domain (spec §4.4).
  registerNode(realizeInstances3DNode);
  registerNode(instanceColor3DNode);
  // M6 (Tier 1 brainstorm): spline bridges, transforms, arrays.
  registerNode(extrudeSpline3DNode);
  registerNode(lathe3DNode);
  registerNode(transform3DNode);
  registerNode(array3DNode);
  registerNode(instanceTransform3DNode);
  // M12: per-copy billboarding.
  registerNode(alignToCamera3DNode);
  // Tier 2 picks (2026-08-11): the 3D→2D points bridge.
  registerNode(projectToScreen3DNode);
  // M8: the bevel (finally).
  registerNode(bevel3DNode);
  // M10: viewport-authored 3D curves.
  registerNode(spline3DNode);
  registerNode(bezierPath3DNode);
  // M11: parametric 3D curve primitives.
  registerNode(rectCurve3DNode);
  registerNode(circleCurve3DNode);
  registerNode(polygonCurve3DNode);
  registerNode(audioSourceNode);
  registerNode(audioBandsNode);
  registerNode(audioPitchNode);
  registerNode(audioSpectralNode);
  registerNode(audioOscillatorNode);
  registerNode(audioFilterNode);
  registerNode(audioNoiseNode);
  registerNode(audioPlayerNode);
  registerNode(audioSynthNode);
  registerNode(audioFmSynthNode);
  registerNode(audioSamplerNode);
  registerNode(audioEq3Node);
  registerNode(audioDistortionNode);
  registerNode(audioBitcrusherNode);
  registerNode(audioCompressorNode);
  registerNode(audioLimiterNode);
  registerNode(audioChannelNode);
  registerNode(audioDelayNode);
  registerNode(audioReverbNode);
  registerNode(audioChorusNode);
  registerNode(audioPhaserNode);
  registerNode(audioMergeNode);
  registerNode(audioCrossfadeNode);
  registerNode(audioStepPatternNode);
  registerNode(audioTransposeNode);
  registerNode(audioLfoNode);
  registerNode(midiEditorNode);
  registerNode(webcamSourceNode);
  registerNode(splineDrawNode);
  registerNode(svgSourceNode);
  registerNode(circleNode);
  registerNode(rectangleNode);
  registerNode(spiralNode);
  registerNode(crossNode);
  registerNode(polygonNode);
  registerNode(starNode);
  registerNode(arcNode);
  registerNode(waveNode);
  registerNode(arrowNode);
  registerNode(imageGenerateNode);
  registerNode(shapeCellsNode);
  registerNode(frameNode);
  registerNode(autoLayoutNode);
  registerNode(sampleAlongPathNode);
  registerNode(resampleNode);
  registerNode(optimizePathNode);
  registerNode(pointsOnPathNode);
  registerNode(offsetPathNode);
  registerNode(repeatPathNode);
  registerNode(trimPathNode);
  registerNode(roundCornersNode);
  registerNode(bezierHandlesNode);
  registerNode(strokeNode);
  registerNode(fillNode);
  registerNode(rasterizeSplineNode);
  registerNode(splineBooleanNode);
  registerNode(splineMergeNode);
  registerNode(blendIntersectionsNode);
  registerNode(splineMorphNode);
  registerNode(splineInterpolateNode);
  registerNode(pointsToSplineNode);
  registerNode(splineTrailsNode);
  registerNode(loopWeaveNode);
  registerNode(setSplineTypeNode);
  registerNode(relaxNode);
  registerNode(ropeSimulatorNode);
  registerNode(rigidBodySimulatorNode);
  registerNode(shortestPathNode);
  registerNode(pointNode);
  registerNode(gridNode);
  registerNode(scatterPointsNode);
  registerNode(copyToPointsNode);
  registerNode(remapNode);
  registerNode(modulatePointsNode);
  registerNode(advectPointsNode);
  registerNode(advectImageNode);
  registerNode(splineFlowFieldNode);
  registerNode(flowObstacleNode);
  registerNode(imageFlowFieldNode);
  registerNode(flowBlurNode);
  registerNode(kuwaharaNode);
  registerNode(flowBilateralNode);
  registerNode(shockFilterNode);
  registerNode(lineArtNode);
  registerNode(modulateSplinesNode);
  registerNode(pointExpressionNode);
  registerNode(pointsToTextNode);
  registerNode(pointLabelsNode);
  registerNode(simulationStartNode);
  registerNode(simulationEndNode);
  registerNode(pointEmitterNode);
  registerNode(imageMaskEmitterNode);
  registerNode(gravityForceNode);
  registerNode(dragForceNode);
  registerNode(pointForceNode);
  registerNode(vortexForceNode);
  registerNode(windForceNode);
  registerNode(turbulenceForceNode);
  registerNode(circleColliderNode);
  registerNode(lineColliderNode);
  registerNode(imageMaskColliderNode);
  registerNode(particleSimulatorNode);
  registerNode(particlesToImageNode);
  registerNode(webgpuParticleTestNode);
  registerNode(reactionDiffusionNode);
  registerNode(watercolorInkNode);
  registerNode(physarumNode);
  registerNode(fluidSimulatorNode);
  registerNode(matterSimulatorNode);
  registerNode(pointsToSurfaceNode);
  registerNode(diffusionCurvesNode);
  registerNode(accumulatorNode);
  registerNode(triggerEnvelopeNode);
  registerNode(sampleHoldNode);
  registerNode(hitRegionNode);
  registerNode(dragPointsNode);
  registerNode(draggableNode);
  registerNode(sharpenNode);
  registerNode(grainNode);
  registerNode(bgRemoveNode);
  registerNode(segmentAnythingNode);
  registerNode(depthAnythingNode);
  registerNode(edgeDetectNode);
  registerNode(objectTrackerNode);
  registerNode(trackerPointNode);
  registerNode(handTrackerNode);
  registerNode(collectNode);
  // Back-compat: "Collect" was named "Group" before node groups
  // (subgraph nesting) claimed that name. Old projects load via the
  // retired type string; `hidden` keeps it out of menus and docs.
  registerNode({ ...collectNode, type: "group", hidden: true });
  // Node groups (subgraph nesting). All hidden from the add menus —
  // groups are created with Cmd+G, boundary nodes are auto-created.
  registerNode(nodeGroupNode);
  registerNode(groupInputNode);
  registerNode(groupOutputNode);
  registerNode(layerNode);
  // Iterate (bounded for-each over a zone — 071826_iterate-node.md,
  // zone presentation 071926_iterate-zone-view.md rev 3). Exactly two
  // nodes: Iteration Input (loop params + per-iteration values) and
  // Iteration Output ("iterate" — the computing shell that anchors
  // membership and collects the result). Both hidden: the add menus'
  // compound "iterate" entry mints the pair together.
  registerNode(iterateNode);
  registerNode(iterateInputNode);
  registerNode(iterateFeedNode);
  registerNode(groupPickNode);
  registerNode(groupLengthNode);
  registerNode(asciiNode);
  registerNode(splitVec2Node);
  registerNode(combineVec2Node);
  registerNode(setPositionNode);
  registerNode(bloomNode);
  registerNode(lensFlareNode);
  registerNode(mergeNode);
  registerNode(blurNode);
  // Gaussian Blur merged into Blur as its "gaussian" mode (080226) — the
  // legacy type stays registered (hidden) so old saves load unchanged.
  registerNode(gaussianBlurLegacyNode);
  registerNode(ditherNode);
  registerNode(posterizeNode);
  registerNode(pixelateNode);
  registerNode(adaptivePixelateNode);
  registerNode(bentoSliceNode);
  registerNode(chromaticAberrationNode);
  registerNode(liquidGlassNode);
  registerNode(colorRampNode);
  registerNode(keyerNode);
  registerNode(colorCorrectionNode);
  registerNode(rgbCurvesNode);
  registerNode(lutNode);
  registerNode(colorSpaceTransformNode);
  registerNode(transformNode);
  registerNode(boundingBoxNode);
  registerNode(mathNode);
  registerNode(rerouteNode);
  registerNode(frameZoneNode);
  registerNode(expressionNode);
  registerNode(trailsNode);
  registerNode(datamoshNode);
  registerNode(stippleNode);
  registerNode(displaceNode);
  registerNode(arrayNode);
  registerNode(mirrorNode);
  registerNode(proximityMergeNode);
  registerNode(connectPointsNode);
  registerNode(splineIntersectionsNode);
  registerNode(splineToPointsNode);
  registerNode(stringArtNode);
  registerNode(lissajous2DNode);
  registerNode(lissajous3DNode);
  registerNode(spaceFillNode);
  registerNode(accretiveGrowthNode);
  registerNode(lSystemNode);
  registerNode(differentialGrowthNode);
  registerNode(behavioralGrowthNode);
  registerNode(jitterNode);
  registerNode(thresholdNode);
  registerNode(constantNode);
  registerNode(animatedValueNode);
  registerNode(timeOffsetNode);
  registerNode(timeOffsetFeedNode);
  registerNode(lfoNode);
  registerNode(wedgeNode);
  registerNode(smoothNode);
  registerNode(switchNode);
  registerNode(sampleTextureAtPointsNode);
  registerNode(setNamedAttributeNode);
  registerNode(attributeMathNode);
  registerNode(attributeBlurNode);
  registerNode(attributeTransferNode);
  registerNode(glslExpressionNode);
  registerNode(mapAttributeNode);
  registerNode(filterPointsNode);
  registerNode(filterSplinesNode);
  registerNode(lerpNode);
  registerNode(polarCoordsNode);
  registerNode(vec2LiteralNode);
  registerNode(vec3LiteralNode);
  registerNode(colorLiteralNode);
  registerNode(stringLiteralNode);
  registerNode(csvNode);
  registerNode(listNode);
  registerNode(numberToStringNode);
  registerNode(randomNode);
  registerNode(compareNode);
  registerNode(logicNode);
  registerNode(clampNode);
  registerNode(floatCurveNode);
  registerNode(sdfCircleNode);
  registerNode(sdfRectangleNode);
  registerNode(sdfUnionNode);
  registerNode(sdfIntersectionNode);
  registerNode(sdfSubtractionNode);
  registerNode(sdfSmoothUnionNode);
  registerNode(sdfRoundNode);
  registerNode(sdfRasterizeNode);
  registerNode(sdfMaterialNode);
  registerNode(sdfShadeNode);
  registerNode(sdfLineSegmentNode);
  registerNode(sdfPolygonNode);
  registerNode(sdfTriangleNode);
  registerNode(sdfStarNode);
  registerNode(sdfSplineNode);
  registerNode(sdfBevelNode);
  registerNode(bevelEmbossNode);
  registerNode(sdfSmoothIntersectionNode);
  registerNode(sdfSmoothSubtractionNode);
  registerNode(sdfMorphNode);
  registerNode(sdfFromImageNode);
  registerNode(sdfTranslateNode);
  registerNode(sdfScaleNode);
  registerNode(sdfRotateNode);
  registerNode(sdfRepeatNode);
  registerNode(sdfMirrorNode);
  registerNode(sdfPolarNode);
  registerNode(sdfTwistNode);
  registerNode(sdfOnionNode);
  registerNode(sdfDisplaceNode);
  registerNode(sdfToDistanceImageNode);
  registerNode(sdfToMaskNode);
  registerNode(sdfToSplineNode);
  registerNode(outputNode);
  registerNode(renderQueueNode);
  registerNode(svgExportNode);
  registered = true;
}
