// Bundles src/lib/glsl-translation/docs/**/*.md into a TS module so the
// editor can serve them over the MCP bridge (get_glsl_docs) and the tsx gates
// can import them without a webpack loader (spec 091626_graph-to-glsl.md §3).
//
//   npx tsx scripts/gen-glsl-docs.mts           write docs.generated.ts
//   npx tsx scripts/gen-glsl-docs.mts --check   exit 1 when it is stale
//
// Frontmatter is the minimal `--- key: value ---` block; `title` is required,
// node docs also carry `type` and `class` (the gate cross-checks them against
// classes.ts).

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const DOCS_DIR = resolve(import.meta.dirname, "../src/lib/glsl-translation/docs");
const OUT = resolve(import.meta.dirname, "../src/lib/glsl-translation/docs.generated.ts");

export interface GlslDocMeta {
  title: string;
  type?: string;
  class?: string;
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (name.endsWith(".md")) out.push(p);
  }
  return out;
}

export function parseFrontmatter(src: string): { meta: Record<string, string>; body: string } {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(src);
  if (!m) return { meta: {}, body: src };
  const meta: Record<string, string> = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z_][\w-]*):\s*(.*)$/.exec(line);
    if (kv) meta[kv[1]] = kv[2].trim().replace(/^"(.*)"$/, "$1");
  }
  return { meta, body: src.slice(m[0].length) };
}

const entries: { slug: string; meta: Record<string, string>; body: string }[] = [];
for (const file of walk(DOCS_DIR)) {
  const slug = relative(DOCS_DIR, file).replace(/\\/g, "/").replace(/\.md$/, "");
  const { meta, body } = parseFrontmatter(readFileSync(file, "utf8"));
  if (!meta.title) {
    console.error(`${slug}.md has no \`title:\` in its frontmatter.`);
    process.exit(1);
  }
  entries.push({ slug, meta, body: body.trim() + "\n" });
}

const lines: string[] = [
  "// GENERATED by scripts/gen-glsl-docs.mts from src/lib/glsl-translation/docs/**/*.md.",
  "// Do not edit — edit the markdown and run `npm run gen:glsl-docs`.",
  "",
  "export interface GlslDoc {",
  "  slug: string;",
  "  title: string;",
  "  type?: string;",
  "  class?: string;",
  "  body: string;",
  "}",
  "",
  "export const GLSL_DOCS: Record<string, GlslDoc> = {",
];
for (const e of entries) {
  lines.push(`  ${JSON.stringify(e.slug)}: {`);
  lines.push(`    slug: ${JSON.stringify(e.slug)},`);
  lines.push(`    title: ${JSON.stringify(e.meta.title)},`);
  if (e.meta.type) lines.push(`    type: ${JSON.stringify(e.meta.type)},`);
  if (e.meta.class) lines.push(`    class: ${JSON.stringify(e.meta.class)},`);
  lines.push(`    body: ${JSON.stringify(e.body)},`);
  lines.push("  },");
}
lines.push("};", "");
const ts = lines.join("\n");

if (process.argv.includes("--check")) {
  let onDisk = "";
  try {
    onDisk = readFileSync(OUT, "utf8");
  } catch {
    // missing ⇒ stale
  }
  if (onDisk !== ts) {
    console.error("docs.generated.ts is stale — run `npm run gen:glsl-docs` and commit.");
    process.exit(1);
  }
  console.log(`docs.generated.ts up to date (${entries.length} docs).`);
} else {
  writeFileSync(OUT, ts);
  console.log(`Wrote ${OUT} (${entries.length} docs: ${entries.map((e) => e.slug).join(", ")})`);
}
