// Emits src/app/theme-tokens.css from the token table, so the CSS ramp and
// the TS ramp can never drift apart. Run `npm run gen:theme-css` after
// editing src/components/effects/theme/tokens.ts.
//
// `--check` exits non-zero if the file on disk is stale (for CI).

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  ACCENTS,
  EXTRA_SURFACES,
  NEUTRAL_RAMP,
  SEMANTIC_ALIASES,
  SHADOWS,
  TINTS,
  WASHES,
  accentVar,
  neutralVar,
  tintVar,
} from "@/components/effects/theme/tokens";
import {
  SOCKET_FALLBACK,
  SOCKET_PALETTE,
  socketVar,
} from "@/components/effects/socketColor";

const OUT = resolve(import.meta.dirname, "../src/app/theme-tokens.css");

function block(mode: "dark" | "light"): string {
  // Tells the UA which way to render everything we don't style ourselves:
  // native scrollbars, form-control internals, spellcheck underlines. Without
  // it the browser keeps painting light-mode scrollbars over a dark editor.
  const lines: string[] = [`  color-scheme: ${mode};`, ""];
  for (let step = 0; step < NEUTRAL_RAMP.length; step++) {
    lines.push(`  ${neutralVar(step)}: ${NEUTRAL_RAMP[step][mode]};`);
  }
  lines.push("");
  for (const [name, pair] of Object.entries(EXTRA_SURFACES)) {
    lines.push(`  ${name}: ${pair[mode]};`);
  }
  for (const [name, pair] of Object.entries(WASHES)) {
    lines.push(`  ${name}: ${pair[mode]};`);
  }
  lines.push("");
  for (const [name, pair] of Object.entries(ACCENTS)) {
    lines.push(`  ${accentVar(name)}: ${pair[mode]};`);
  }
  lines.push("");
  for (const [name, pair] of Object.entries(TINTS)) {
    lines.push(`  ${tintVar(name)}: ${pair[mode]};`);
  }
  lines.push("");
  // Socket hues: same hue in both modes, lightness capped in light mode.
  for (const [type, pair] of Object.entries(SOCKET_PALETTE)) {
    lines.push(`  ${socketVar(type)}: ${pair[mode]};`);
  }
  lines.push(`  --tb-s-fallback: ${SOCKET_FALLBACK[mode]};`);
  lines.push("");
  for (const [name, pair] of Object.entries(SHADOWS)) {
    lines.push(`  ${name}: ${pair[mode]};`);
  }
  return lines.join("\n");
}

const aliasBlock = Object.entries(SEMANTIC_ALIASES)
  .map(([alias, target]) => `  ${alias}: var(${target});`)
  .join("\n");

const css = `/* GENERATED by scripts/gen-theme-css.mts — do not edit by hand.
   Source of truth: src/components/effects/theme/tokens.ts
   Regenerate with: npm run gen:theme-css

   Dark is the :root default, so server-rendered and pre-hydration paint
   match today's editor exactly. The pre-paint script in app/layout.tsx flips
   [data-theme="light"] before first paint; theme.ts layers the brightness
   trim on top as inline custom properties. */

:root {
${block("dark")}

  /* Semantic aliases — prefer these in new code. */
${aliasBlock}
}

:root[data-theme="light"] {
${block("light")}
}
`;

if (process.argv.includes("--check")) {
  const onDisk = (() => {
    try {
      return readFileSync(OUT, "utf8");
    } catch {
      return "";
    }
  })();
  if (onDisk !== css) {
    console.error(
      "theme-tokens.css is stale — run `npm run gen:theme-css` and commit."
    );
    process.exit(1);
  }
  console.log("theme-tokens.css up to date.");
} else {
  writeFileSync(OUT, css);
  console.log(
    `Wrote ${OUT} (${NEUTRAL_RAMP.length} ramp steps, ${
      Object.keys(ACCENTS).length
    } accents, ${Object.keys(TINTS).length} tints)`
  );
}
